mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^' , include('polls.urls' , namespace = "polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns,url
from django.contrib.auth.decorators import login_required
from polls import views
 
urlpatterns = patterns('',
	
	url(r'^feedback',login_required(views.IndexView2.as_view()) , name = 'index2'),
	
	url(r'^$',views.IndexView.as_view() , name = 'index'),
		# ex: /polls/5/
	url(r'^(?P<pk>\d+)/$',login_required (views.DetailView.as_view()), name='detail'),
    # ex: /polls/5/results/
	url(r'^(?P<pk>\d+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    # ex: /polls/5/vote/
	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
	
	url(r'^login/$' , views.call_login , name = 'loginpage'),
	
	url(r'^auth/$' , views.afterlogin , name = 'afterloginpage'),
	
	url(r'^creatinguser/$' , views.creatinguser , name = 'creatinguser'),
	
	url(r'^signup/$' , views.call_signup , name = 'signup'),
	
	url(r'^logout/$' , views.logout_view , name = 'logout'),
	
	url(r'^profilepage/$' , views.profilepage , name = 'profilepage'),
	url(r'^editprofile/$' , views.editprofile , name = 'editprofile'),
	
	url(r'^changepwd/$' , views.changepassword , name = 'changepwd'),
	
	url(r'^changepwdpage/$' , views.changepasswordpage , name = 'changepwdpage'),
	url(r'^library/$' , views.library , name = 'library'),
	
	)
	
	
	


polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question_text
	
	def was_published_recently(self):
			now = timezone.now()
			return  now - datetime.timedelta(days=1) <= self.pub_date <= now 
			was_published_recently.admin_order_field = 'pub_date'
			was_published_recently.boolean = True	
			was_published_recently.short_description = 'Published recently?'	
		
class Choice(models.Model):
		question = models.ForeignKey(Question)
		choice_text = models.CharField(max_length = 200)
		votes = models.IntegerField(default = 0)
		def __unicode__(self):
			return self.choice_text
	

polls/views.py
from django.utils import timezone 
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import RequestContext, loader
from polls.models import Choice,Question
from django.shortcuts import render,get_object_or_404,redirect,render_to_response
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError

def library(request):
 return render(request,'polls/library.html')

def call_login(request):
 return render(request,'polls/login.html')
 
def call_signup(request):
 return render(request,'polls/signup.html')
@login_required
def profilepage(request):
 return render(request,'polls/profilepage.html')

@login_required 
def editprofile(request):
 loggedinuser = request.user
 firstname = request.POST['firstname']
 lastname = request.POST['lastname']
 email = request.POST['email']
 
 if firstname and lastname and email:
  loggedinuser.first_name = firstname
  loggedinuser.last_name = lastname
  loggedinuser.email = email
  loggedinuser.save()
  return HttpResponseRedirect(reverse('polls:profilepage'))
 else:
  return render(request,"polls/profilepage.html", { 'message' : "All fields are necessary."} )
  

def afterlogin(request):
 username = request.POST['username']
 password = request.POST['password']
 user = authenticate(username = username , password = password)
 if user is not None:
  if user.is_active:
   login(request,user)
   return HttpResponseRedirect(reverse('polls:index2')) 
  else: 
   return render(request,"polls/login.html", { 'message' : "The password is valid, but the account has been disabled!" })
  
 else:
  return render(request,"polls/login.html", { 'message' : "Invalid Details." })

@login_required
def logout_view(request):
 logout(request)
 return HttpResponseRedirect(reverse('polls:index'))
 
@login_required
def changepasswordpage(request):
 return render(request,'polls/changepwdpage.html')

@login_required
def changepassword(request):
 loggedinuser = request.user
 oldpassword = request.POST['oldpassword']
 password1 = request.POST['password1']
 password2 = request.POST['password2']  
 user = authenticate(username = loggedinuser.username , password = oldpassword)
 if user is not None:
  if user.is_active:
   if password1 == password2 and password1 and password2:
    
    user.set_password(password1)
    user.save()
    login(request,user)
    return render(request,"polls/changepwdpage.html", { 'message' : "Password Successfully Changed." })
   else:
    return render(request,"polls/changepwdpage.html", { 'message' : "Password Didnot match."})
  else:
   logout(request,user)
   return render(request,"polls/changepwdpage.html", { 'message' : "The password is valid, but the account has been disabled!" })
 else:
  return render(request,"polls/changepwdpage.html", { 'message' : "Password Entered is Incorrect." })

 
 

 
def creatinguser(request):

 email = request.POST['email']
 firstname = request.POST['firstname']
 lastname = request.POST['lastname']
 username = request.POST['username']
 password1 = request.POST['password1']
 password2 = request.POST['password2']
 if password1 and password2 and firstname and username and lastname and email:
  if password1 == password2:
   user = User.objects.create_user(username,email,password1)
   user.first_name = firstname
   user.last_name = lastname
   user.save()
   return HttpResponseRedirect(reverse('polls:index'))
  else :
   return render(request,"polls/signup.html", { 'message' : "Passwords didn't match." })
 else:
   return render(request,"polls/signup.html", { 'message' : "All fields are necessary." })
 


class IndexView(generic.ListView):
 template_name = 'polls/index.html'
 context_object_name = 'latest_question_list'
 
 def get_queryset(self):
  """Return the last five punlished questions"""
  return Question.objects.filter(
   pub_date__lte = timezone.now()
   ).order_by('pub_date')[:6]



class IndexView2(generic.ListView):
 template_name = 'polls/index2.html'
 context_object_name = 'latest_question_list'
 
 def get_queryset(self):
  """Return the last five punlished questions"""
  return Question.objects.filter(
   pub_date__lte = timezone.now()
   ).order_by('pub_date')[:6]


class DetailView(generic.DetailView):
 model = Question
 template_name  = 'polls/detail.html'
 def get_queryset(self):
  return Question.objects.filter(pub_date__lte = timezone.now())

class ResultsView(generic.DetailView):
 model = Question
 template_name = 'polls/results.html'

 


#def index(request):
# latest_question_list = Question.objects.order_by('-pub_date')[:5]
# template = loader.get_template('polls/index.html')
# context = RequestContext(request , {
#  'latest_question_list' : latest_question_list,
# })
# return HttpResponse(template.render(context))
 
  # def index(request):
  # latest_question_list = Question.objects.order_by('-pub_date')[:5]
  #  context = {'latest_question_list': latest_question_list}
  #  return render(request, 'polls/index.html', context)

#def results(request,question_id):
#  response = "You're looking at the results of question %s."
#  return HttpResponse(response  %question_id)
@login_required
def vote(request, question_id):
 p = get_object_or_404(Question, pk = question_id)
 try:
  selected_choice = p.choice_set.get(pk = request.POST['choice'])
 except (KeyError ,Choice.DoesNotExist):
  #redisplaying the voting form
  return render(request , 'polls/detail.html' , {
   'question':p,
   'error_message': "You didn't select a choice. ",
  })
 else:
  selected_choice.votes += 1
  selected_choice.save()
  # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
       # user hits the Back button.  
 return HttpResponseRedirect(reverse('polls:results', args= (p.id,)))
 
#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#   return render(request, 'polls/results.html', {'question': question}) 
 
#raising an error 
#def detail(request, question_id):
 #   try: 
  #      question = Question.objects.get(pk=question_id)
   # except Question.DoesNotExist:
    #    raise Http404("Question does not exist")
    #return render(request, 'polls/detail.html', {'ques': question})
 
 
#alternate shortcut better option
 
#def detail(request,question_id):
# question = get_object_or_404(Question , pk = question_id)
# return render(request , 'polls/detail.html' , {'question' : question} )

polls/templates/polls/changepwdpage.html
<!DOCTYPE html>
{% load static from staticfiles %}

 <link href="{% static 'polls/css/bootstrap.css' %}" rel="stylesheet">
 <script src="{% static 'polls/js/jquery.js' %}"></script>
 <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
 <script src="{% static 'polls/js/bootstrap.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/font-awesome.css' %}">
 <script src="{% static 'polls/js/jquery-1.7.min.js' %}" type="text/javascript" charset="utf-8"></script>
 <script src="{% static 'polls/js/jquery.featureCarousel.js' %}" type="text/javascript" charset="utf-8"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/login.css' %}">
 
 <script type="text/javascript" src="{% static 'polls/js/script.js' %}"></script>

<body>
<style type="text/css">
 .navbar-inverse .navbar-nav>li>a{
 color: white
}
</style>
 <div class="container-fluid header white-text uppercase" >
  <nav class="navbar navbar-inverse navbar-fixed-top transparent-background" role="navigation" style="background-color:#222">
   <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href=""><img src="{% static 'polls/images/logo.png' %}" style="width:50px"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right" >
      <li><a href="{% url 'polls:index2' %}"><img src='{% static 'polls/images/work.png' %}'>&nbsp;&nbsp;Hi , {{ user.get_username }}</a></li>
      <li><a href="{% url 'polls:profilepage' %}"><img src='{% static 'polls/images/nav1.png' %}'>&nbsp;&nbsp;Edit Profile</a></li>
      <li><a href="{% url 'polls:changepwdpage' %}"><img src='{% static 'polls/images/nav2.png' %}'>&nbsp;&nbsp;Change Password</a></li>
      <li><a href="{% url 'polls:library' %}"><img src='{% static 'polls/images/nav3.png' %}'>&nbsp;&nbsp;Library</a></li>
      <li><a href="{% url 'polls:logout' %}"><img src='{% static 'polls/images/nav4.png' %}'>&nbsp;&nbsp;Logout</a></li>
     </ul>
    </div>
   </div>
  </nav>
</div>

  <div class="container-fluid bg" style="position:absolute;top:0%;width:100%;margin:auto;height:100%">
      <div class="col-md-12 text-center" style="padding-top:20vh;">
            <a href="" style="text-align:center;"><img src="{% static 'polls/images/home.png' %}" alt="" width="130px"></a>
    
    </div>
    
{% if message %}<p class="error"><strong>{{message}}</strong></p> {% endif %}
    <form class="form-horizontal" action="{% url 'polls:changepwd' %}" method="post">
     {% csrf_token %}
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
              <div class="form-group ">
                <div class="col-sm-10 col-sm-offset-1 toppad">
                  <input type="password" name="oldpassword"  method="POST" class="form-control name" placeholder="Old Password">
                </div>
              </div> 
              <div class="form-group">
                <div class="col-sm-10 col-sm-offset-1">          
                  <input type="password" name="password1"  method="POST" class="form-control name" placeholder="New Password">
                  </div>
              </div> 
              <div class="form-group">
                <div class="col-sm-10 col-sm-offset-1">          
                  <input type="password" name="password2"  method="POST" class="form-control name" placeholder="Confirm New Password">
                  </div>
              </div> 
              
              <div class="col-sm-12 btn1" style="margin-top:20px;">
                <input class="cta" type="submit" name="changepwd" value="Change Password"><span class="typoround-light-small"></span>
              </div>
                
          </div>
        </div>
      </div>
      </form>
    </dvi>

polls/templates/polls/detail.html
<!DOCTYPE html>
{% load static from staticfiles %}

 <link href="{% static 'polls/css/bootstrap.css' %}" rel="stylesheet">
 <script src="{% static 'polls/js/jquery.js' %}"></script>
 <script src="{% static 'polls/js/bootstrap.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/font-awesome.css' %}">
 <script src="{% static 'polls/js/jquery-1.7.min.js' %}" type="text/javascript" charset="utf-8"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/signup.css' %}">
 
 <script type="text/javascript" src="{% static 'polls/js/script.js' %}"></script>

<body>
<style type="text/css">
 .navbar-inverse .navbar-nav>li>a{
 color: white
}
</style>
 <div class="container-fluid header white-text uppercase">
  <nav class="navbar navbar-inverse navbar-fixed-top ransparent-background" role="navigation">
   <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'polls:index' %}"><img src="{% static 'polls/images/logo.png' %}" style="width:50px"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'polls:index2' %}"><img src='{% static 'polls/images/work.png' %}'>&nbsp;&nbsp;Hi , {{ user.get_username }}</a></li>
      <li><a href="{% url 'polls:profilepage' %}"><img src='{% static 'polls/images/nav1.png' %}'>&nbsp;&nbsp;Edit Profile</a></li>
      <li><a href="{% url 'polls:changepwdpage' %}"><img src='{% static 'polls/images/nav2.png' %}'>&nbsp;&nbsp;Change Password</a></li>
      <li><a href="{% url 'polls:library' %}"><img src='{% static 'polls/images/nav3.png' %}'>&nbsp;&nbsp;Library</a></li>
      <li><a href="{% url 'polls:logout' %}"><img src='{% static 'polls/images/nav4.png' %}'>&nbsp;&nbsp;Logout</a></li>
     </ul>
    </div>
   </div>
  </nav>

  <div class="container center-align uppercase white-text" style="margin-top:15%">
   <div class="row">
    <div class="col-md-12" style="font-size:50px;font-weight:700">
       {{question.question_text }}
    </div>
   </div>

   <div class="row">
    <div class="col-md-12" style="font-size:20px">
     <div class="box_question">
      <form action= "{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}

         <div>
           <ol type="I">
            {% for choice in question.choice_set.all %}
              <li>
               <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}" />
                <label for="choice{{ forloop.counter }}" > {{ choice.choice_text }}
                </label>
                 </br>
              </li>
              <br>
            {% endfor %}
           </ol>
        <br><br>
        <div class="col-sm-12 btn1" style="margin-top:-60px;">
            {% if error_message %}<p class="error" style="color:red;"> <strong>{{error_message}}</strong></p> {% endif %}

           <input type="submit" value="Submit" class="cta shadow">
        </div>
        </div>
         </form>       
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="container margin-bottom-50" style="margin-top:25%">
  <div class="row">
   <div class="col-md-12 center-align uppercase margin-bottom-50" style="color:#ADABAC;font-size:25px;">
    What Do you want?
   </div>
  </div>
  <div class="row">
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/interior.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Interior Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/home.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Home Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/landscape.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Landscape Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/plan.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style=" margin-top: 15px;font-size: 20px;">
      Plan Modification
     </div>
    </div>
   </div>
  </div>
 </div>
  
 <footer style="padding-top: 20px;background-color: #8E7CB9;padding-bottom: 20px;">
  <div class="container uppercase white-text">
   <div class="row">
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       <img src="{% static 'polls/images/logo.png' %}">
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       Houzzane
      </div>
     </div>
    </div>
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       about
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       terms of use
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       we are hiring
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       offers
      </div>
     </div>
    </div>
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       for architects
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       payments
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       contact us
      </div>
     </div> 
    </div>
   </div>
  </div>
 </footer>

 

polls/templates/polls/index2.html
<!DOCTYPE html>
{% load static from staticfiles %}

 <link href="{% static 'polls/css/bootstrap.css' %}" rel="stylesheet">
 <script src="{% static 'polls/js/jquery.js' %}"></script>
 <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
 <script src="{% static 'polls/js/bootstrap.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/font-awesome.css' %}">
 <script src="{% static 'polls/js/jquery-1.7.min.js' %}" type="text/javascript" charset="utf-8"></script>
 <script src="{% static 'polls/js/jquery.featureCarousel.js' %}" type="text/javascript" charset="utf-8"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
 <script type="text/javascript" src="{% static 'polls/js/script.js' %}"></script>

<body>
<style type="text/css">
 .navbar-inverse .navbar-nav>li>a{
 color: white
}
</style>
 <div class="container-fluid header white-text uppercase">
  <nav class="navbar navbar-inverse navbar-fixed-top ransparent-background" role="navigation">
   <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'polls:index' %}"><img src="{% static 'polls/images/logo.png' %}" style="width:50px"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'polls:index2' %}"><img src='{% static 'polls/images/work.png' %}'>&nbsp;&nbsp;Hi , {{ user.get_username }}</a></li>
      <li><a href="{% url 'polls:profilepage' %}"><img src='{% static 'polls/images/nav1.png' %}'>&nbsp;&nbsp;Edit Profile</a></li>
      <li><a href="{% url 'polls:changepwdpage' %}"><img src='{% static 'polls/images/nav2.png' %}'>&nbsp;&nbsp;Change Password</a></li>
      <li><a href="{% url 'polls:library' %}"><img src='{% static 'polls/images/nav3.png' %}'>&nbsp;&nbsp;Library</a></li>
      <li><a href="{% url 'polls:logout' %}"><img src='{% static 'polls/images/nav4.png' %}'>&nbsp;&nbsp;Logout</a></li>
     </ul>
    </div>
   </div>
  </nav>

  <div class="container center-align uppercase white-text" style="margin-top:15%">
   <div class="row">
    <div class="col-md-12" style="font-size:50px;font-weight:700">
      <marquee>
        <h4>(Click the questions for Feedback.You can answer as many question you want to.)</h4>
      </marquee>
    </div>
   </div>
   <div class="row">
    <div class="col-md-12" style="font-size:20px">
     <div class="box_question">
      {% if latest_question_list %}
        <ul>_
         {% for question in latest_question_list %}
           <li>
            <a href = "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
           </li>
           <br><br>
         {% endfor %}
        </ul>
      {% else %}
        <p>No polls are available.</p>
      {% endif %}
     </div>
    </div>
   </div>
  </div>
 </div>

<div class="container-fluid margin-bottom-50 refer" style="margin-top:15%">
  <div class="container white-text">
   <div class="row">
    <div class="col-md-6">
     <div class="row" style="margin-bottom:20px">
      <div class="col-md-12 uppercase"  style="font-size:30px">
       refer a friend
      </div>
     </div>
     <div class="row" style="margin-bottom:20px">
      <div class="col-md-12 uppercase"  style="font-size:20px">
       and get a chance to earn
      </div>
     </div>
     <div class="row" style="margin-bottom:20px">
      <div class="col-md-12 uppercase">
       <button type="button" class="btn link-btn" style="background-color:#E0A2B3">Know More</button>
      </div>
     </div>
    </div>

    <div class="col-md-6">
     <img src="{% static 'polls/images/refer.png' %}" width="100%">
    </div>
   </div>
  </div>
 </div>



 <div class="container margin-bottom-50">
  <div class="row">
   <div class="col-md-12 center-align uppercase margin-bottom-50" style="color:#ADABAC;font-size:25px;">
    What Do you want?
   </div>
  </div>
  <div class="row">
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/interior.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Interior Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/home.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Home Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/landscape.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style="margin-top: 15px;font-size: 20px;">
      Landscape Design
     </div>
    </div>
   </div>
   <div class="col-md-3 center-align whatuwant">
    <div class="row">
     <div class="col-md-12">
      <img src="{% static 'polls/images/plan.png' %}">
     </div>
    </div>
    <div class="row">
     <div class="col-md-12" style=" margin-top: 15px;font-size: 20px;">
      Plan Modification
     </div>
    </div>
   </div>
  </div>
 </div>
  
 <footer style="padding-top: 20px;background-color: #8E7CB9;padding-bottom: 20px;">
  <div class="container uppercase white-text">
   <div class="row">
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       <img src="{% static 'polls/images/logo.png' %}">
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       Houzzane
      </div>
     </div>
    </div>
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       about
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       terms of use
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       we are hiring
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       offers
      </div>
     </div>
    </div>
    <div class="col-md-4">
     <div class="row">
      <div class="col-md-12">
       for architects
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       payments
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       contact us
      </div>
     </div> 
    </div>
   </div>
  </div>
 </footer>

 